---
# Check for a condition in a task
# Usage: ansible-playbook use_conditionals.yml
- name: Use conditionals
  hosts: managed_node1
  gather_facts: false
  vars:
    planet: "Mars"
  tasks:
    - name: Show message based on a condition (if)
      ansible.builtin.debug:
        msg: "{{ 'Hi!' if planet == 'Mars' }}"

    - name: Show alternate message (if-else)
      ansible.builtin.debug:
        msg: >-
          {{ 'Welcome to Mars!' if planet == 'Mars' else
          'Welcome to Earth!' }}

    - name: Show alternate message (ternary filter)
      ansible.builtin.debug:
        msg: >-
          {{ (planet == 'Mars') | ternary('Welcome to Mars!',
          'Welcome to Earth!') }}

    - name: Perform a task if a condition is met (when)
      ansible.builtin.debug:
        msg: "Condition met!"
      when: planet == 'Mars'

    - name: Skip a task if a condition is not met (when)
      ansible.builtin.debug:
        msg: "Condition not met!"
      when: planet == 'Earth'
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
