---
# Set and show a list of dictionaries
# Usage: ansible-playbook use_list_dicts.yml
- name: Use list of dictionaries
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Set and show a dictionary
      vars:
        planets:
          - planet: "Earth"
            diameter: 12756
          - planet: "Mars"
            diameter: 6792
      ansible.builtin.debug:
        msg:
          - "{{ planets }}"
          - "{{ planets[0]['planet'] }} is
            {{ planets[0]['diameter'] }} km in diameter."
          - "{{ planets[1].planet }} is
            {{ planets[1].diameter }} km in diameter."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
