---
# Reusable list of tasks
# Usage:
# ansible.builtin.import_tasks:
#   file: tasks.yml
# ansible.builtin.include_tasks:
#   file: tasks.yml
- name: Show a message
  ansible.builtin.debug:
    msg: "Hello, {{ shared_var }}!"

- name: Show another message
  ansible.builtin.debug:
    msg:
      - "I am an external task."
      - "{{ item â”‚ default('Earth') }} is a planet."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
