---
# Create a subdirectory in the current working directory
# Usage: ansible-playbook create_directory.yml
- name: Create a directory
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: demo
        state: directory
        # Allow directory traversal
        mode: '0755'
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
