---
# Use this playbook to demo import_playbook
# Usage: ansible.builtin.import_playbook: playbook.yml
- name: Demo playbook
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Show a message
      ansible.builtin.debug:
        msg: "I am an external playbook."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
