---
# This playbook runs multiple plays
# Usage: ansible-playbook run_multiple_plays.yml
- name: Run a play
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Show a message in the first play
      ansible.builtin.debug:
        msg: "This is the first play."

- name: Run another play
  hosts: managed_node1
  gather_facts: false
  tasks:
    - name: Show a message in the second play
      ansible.builtin.debug:
        msg: "This is the second play."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
