---
# Test variables against a common expression
# https://jinja.palletsprojects.com/en/3.1.x/templates/#list-of-builtin-tests
# Usage: ansible-playbook test_variables.yml
- name: Test variables
  hosts: managed_node1
  gather_facts: false
  vars:
    planet: "Mars"
    diameter: 6792
    hours_per_day: 24.7
    rings: false
    moons:
      - "Phobos"
      - "Deimos"
  tasks:
    - name: Test for type
      ansible.builtin.debug:
        msg:
          - "'Mars' is str: {{ planet is string }}"
          - "'Mars' is int: {{ planet is integer }}"
          - "'Mars' is not int: {{ planet is not integer }}"

    - name: Test for content
      ansible.builtin.debug:
        msg:
          - "'r' in 'Mars': {{ 'r' in planet }}"
          - "'t' in 'Mars': {{ 't' in planet }}"
          - "No 't' in 'Mars': {{ 't' not in planet }}"
          - >-
            Phobos is a Martian moon: {{ 'Phobos' in moons }}
          - "Titan is a Martian moon: {{ 'Titan' in moons }}"
          - >-
            Titan is not a Martian moon:
            {{ 'Titan' not in moons }}

    - name: Perform other tests
      ansible.builtin.debug:
        msg:
          - "6792 is even: {{ diameter is even }}"
          - "24.7 is float: {{ hours_per_day is float }}"
          - "Mars had rings: {{ rings is true }}"
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
